<?php
/*
 * Documento   : nuevoModulo
 * Creado      : 11-jul-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$grabar = Session::getPermiso('MNUGR');

$Form = new FormFactory([
            "title"=>M_FG_MOD_TITLTE,
            "alias"=>T3,
            "ajaxSubmit"=>"Menu.postNewModulo();",
            "attr"=>[
                "id"=>"formNuevoModulo",
                "name"=>"formNuevoModulo",
                "class"=>"modal fade"
            ],
            "noSubmit"=>$grabar['permiso'] //cuando no tiene permiso de grabar, el enter en elementos no funciona
        ]);

$Form->addField([
    "label"=>[
        "label"=>M_FG_MOD_L_MOD,
        "attr"=>["class"=>"label col col-2"]
    ],
    "field"=>[
        "attr"=>[
            "type"=>"text",
            "id"=>"txt_modulo",
            "name"=>"txt_modulo"
        ],
        "help"=>M_FE_DOM_H_MOD2,
        "iconrequired"=>true,
        "validate"=>["required:true","minlength:3"]
    ]
]);

$Form->addField([
    "label"=>[
        "label"=>CK_ACTIVO,
        "attr"=>["class"=>"label col col-2"]
    ],
    "field"=>[
        "csswidth"=>"col col-3",
        "attr"=>[
            "type"=>"checkbox",
            "id"=>"chk_activo",
            "name"=>"chk_activo",
            "value"=>"A",
            "checked"=>true
        ]
    ]
]);

if($grabar['permiso']){
    $Form->addButton([
        "label"=>$grabar['accion'],
        "icon"=>$grabar['icono'],
        "attr"=>[
            "id"=>"btnGrabaModulo",
            "type"=>"submit",
            "class"=>$grabar['theme']
        ]
    ]);
}

$Form->addButton([
    "label"=>BTN_CLOSE,
    "icon"=>ICON_CLOSE,
    "attr"=>[
        "type"=>"button",
        "class"=>THEME_CLOSE
    ]
]);

$Form->view(); 