<?php

/*
 * Documento   : editarModulo
 * Creado      : 11-jul-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$editar = Session::getPermiso('MNUACT');

$found = MenuController::findModulo();

$Form = new FormFactory([
            "title"=>M_FE_MOD_TITLTE,
            "alias"=>T3,
            "ajaxSubmit"=>"Menu.postEditModulo();",
            "attr"=>[
                "id"=>"formEditModulo",
                "name"=>"formEditModulo",
                "class"=>"modal fade"
            ],
            "noSubmit"=>$editar['permiso'] //cuando no tiene permiso de grabar, el enter en elementos no funciona
        ]);

$Form->addField([
    "label"=>[
        "label"=>M_FG_MOD_L_MOD,
        "attr"=>["class"=>"label col col-2"]
    ],
    "field"=>[
        "attr"=>[
            "type"=>"text",
            "id"=>"txt_modulo",
            "name"=>"txt_modulo",
            "value"=>$found['modulo']
        ],
        "help"=>M_FE_DOM_H_MOD2,
        "iconrequired"=>true,
        "validate"=>["required:true","minlength:3"]
    ]
]);

$Form->addField([
    "label"=>[
        "label"=>CK_ACTIVO,
        "attr"=>["class"=>"label col col-2"]
    ],
    "field"=>[
        "csswidth"=>"col col-3",
        "attr"=>[
            "type"=>"checkbox",
            "id"=>"chk_activo",
            "name"=>"chk_activo",
            "value"=>"A",
            "checked"=>($found['estado'] == 'A')?true:false
        ]
    ]
]);

if($editar['permiso']){
    $Form->addButton([
        "label"=>$editar['accion'],
        "icon"=>$editar['icono'],
        "attr"=>[
            "id"=>"btnEditarModulo",
            "type"=>"submit",
            "class"=>$editar['theme']
        ]
    ]);
}

$Form->addButton([
    "label"=>BTN_CLOSE,
    "icon"=>ICON_CLOSE,
    "attr"=>[
        "type"=>"button",
        "class"=>THEME_CLOSE
    ]
]);

$Form->view(); 