<?php
/*
 * Documento   : editarMenuPrincipal
 * Creado      : 11-jul-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$edit = Session::getPermiso('MNUACT');

$found = MenuController::findMenu();

$Form = new FormFactory([
            "title"=>M_FE_MNU_TITLTE,
            "alias"=>T3,
            "ajaxSubmit"=>"Menu.postEditarMenu();",
            "attr"=>[
                "id"=>"formEditMenu",
                "name"=>"formEditMenu",
                "class"=>"modal fade"
            ],
            "noSubmit"=>$edit['permiso'] //cuando no tiene permiso de grabar, el enter en elementos no funciona
        ]);

$Form->addField([
    "label"=>[
        "label"=>M_FE_MNU_L_MNU,
        "attr"=>["class"=>"label col col-2"]
    ],
    "field"=>[
        "attr"=>[
            "type"=>"text",
            "id"=>"txt_menu",
            "name"=>"txt_menu",
            "value"=>$found['menu']
        ],
        "help"=>M_FE_MNU_H_MNU,
        "iconrequired"=>true,
        "validate"=>["required:true","minlength:3"]
    ]
]);

$Form->addField([
    "label"=>[
        "label"=>CK_ACTIVO,
        "attr"=>["class"=>"label col col-2"]
    ],
    "field"=>[
        "csswidth"=>"col col-3",
        "attr"=>[
            "type"=>"checkbox",
            "id"=>"chk_activo",
            "name"=>"chk_activo",
            "value"=>"A",
            "checked"=>($found['estado'] == 'A')?true:false
        ]
    ]
]);

if($edit['permiso']){
    $Form->addButton([
        "label"=>$edit['accion'],
        "icon"=>$edit['icono'],
        "attr"=>[
            "id"=>"btnEditarMenuPri",
            "type"=>"submit",
            "class"=>$edit['theme']
        ]
    ]);
}

$Form->addButton([
    "label"=>BTN_CLOSE,
    "icon"=>ICON_CLOSE,
    "attr"=>[
        "type"=>"button",
        "class"=>THEME_CLOSE
    ]
]);

$Form->view();