<?php
/*
 * Documento   : nuevoDominio
 * Creado      : 10-jul-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$grabar = Session::getPermiso('MNUGR');

$Form = new FormFactory([
                "title"=>M_FG_DOM_TITLTE,
                "alias"=>T3,
                "ajaxSubmit"=>"Menu.postNewDominio();",
                "attr"=>[
                    "id"=>"formNuevoDominio",
                    "name"=>"formNuevoDominio",
                    "class"=>"modal fade"
                ],
                "noSubmit"=>$grabar['permiso'] //cuando no tiene permiso de grabar, el enter en elementos no funciona
            ]);

$Form->addField([
    "label"=>[
        "label"=>M_FG_DOM_L_DOM,
        "attr"=>["class"=>"label col col-2"]
    ],
    "field"=>[
        "attr"=>[
            "type"=>"text",
            "id"=>"txt_dominio",
            "name"=>"txt_dominio"
        ],
        "help"=>M_FE_DOM_H_MOD,
        "iconrequired"=>true,
        "validate"=>["required:true","minlength:5"]
    ]
]);

$Form->addField([
    "label"=>[
        "label"=>M_FG_DOM_L_ICON,
        "attr"=>["class"=>"label col col-2"]
    ],
    "field"=>[
        "csswidth"=>"col col-6",
        "attr"=>[
            "type"=>"text",
            "id"=>"txt_icono",
            "name"=>"txt_icono"
        ],
        "help"=>M_FG_DOM_H_ICON,
        "iconrequired"=>true,
        "validate"=>["required:true","minlength:5"]
    ]
]);

$Form->addField([
    "label"=>[
        "label"=>CK_ACTIVO,
        "attr"=>["class"=>"label col col-2"]
    ],
    "field"=>[
        "csswidth"=>"col col-3",
        "attr"=>[
            "type"=>"checkbox",
            "id"=>"chk_activo",
            "name"=>"chk_activo",
            "value"=>"A",
            "checked"=>true
        ]
    ]
]);

if($grabar['permiso']){
    $Form->addButton([
        "label"=>$grabar['accion'],
        "icon"=>$grabar['icono'],
        "attr"=>[
            "id"=>"btnGrabaDominio",
            "type"=>"submit",
            "class"=>$grabar['theme']
        ]
    ]);
}

$Form->addButton([
    "label"=>BTN_CLOSE,
    "icon"=>ICON_CLOSE,
    "attr"=>[
        "type"=>"button",
        "class"=>THEME_CLOSE
    ]
]);

$Form->view(); 