<?php
/*
 * Documento   : nuevoMenuPrincipal
 * Creado      : 11-jul-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$grabar = Session::getPermiso('MNUGR');
?>
<form id="<?php echo T3; ?>formNewMenu" name="<?php echo T3; ?>formNewMenu" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo M_FG_MNU_TITLTE?></h4>
            </div>
            <div class="modal-body smart-form">
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo M_FE_MNU_L_MNU; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-question-circle"></i>
                                <input type="text" id="<?php echo T3; ?>txt_menu" name="<?php echo T3; ?>txt_menu" >
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo M_FE_MNU_H_MNU; ?></b>
                                <div class="obligar"></div>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2"></label>
                        <div class="col col-3">
                            <label class="checkbox">
                                <input type="checkbox" checked="checked" name="<?php echo T3; ?>chk_activo" id="<?php echo T3; ?>chk_activo" value="A"></input>
                                <i></i>
                                <?php echo CK_ACTIVO?>
                            </label>
                        </div>
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <?php if($grabar['permiso']):?>
                <button id="<?php echo T3; ?>btnGrabaMenuPri" type="submit" class="<?php echo $grabar['theme']; ?>">
                    <i class="<?php echo $grabar['icono']; ?>"></i> <?php echo $grabar['accion']; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

<!-- si no riene permiso se anula submit desde cualquier input -->
<?php if(!$grabar['permiso']): ?>
<script>
    simpleScript.noSubmit('#<?php echo T3; ?>formNewMenu');
</script>
<?php endif; ?>
<script>
    $('.xhelp').tooltip({placement:'right'});
    $('#<?php echo T3; ?>formNewMenu').validate({
        // Rules for form validation
        rules : {
                <?php echo T3; ?>txt_menu : {
                        required : true,
                        minlength: 3
                }
        },

        // Do not change code below
        errorPlacement : function(error, element) {
                error.insertAfter(element.parent());
        },

        submitHandler: function(){
            Menu.postNewMenu();
        }   
    });
</script>
</form>