<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 18-03-2015 23:03:01 
* Descripcion : indexEmpleados.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("ACCNEW");
$eliminar = Session::getPermiso("ACCDE");
    
echo SimpleForm::widgetOpen(array(
        "id"=>T2,
        "title"=>'acc'
    )); 
?>


<div id="<?php echo T2; ?>gridAcciones"></div>
<br><br><br><br>
<div id="<?php echo T2; ?>gridAcciones2"></div>



<div id="<?php echo T2; ?>gridAcciones_btns">
    <!-- verificar permisos -->
    <?php if($nuevo["permiso"]): ?>
    <button id="<?php echo T2; ?>btnNewEmpleados" type="button" onclick="" class="<?php echo $nuevo["theme"]; ?>">
        <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
    </button>
    <?php endif; ?>
</div>
<table  class="table table-striped table-hover table-condensed dataTable table-bordered" ></table>    
<?php echo SimpleForm::widgetClose(); ?>
<script>
axScript.removeAttr.click({
    container: "#"+tabs.T2+"gridAcciones_tools",
    typeElement: "button"
});      
</script>




<div id="<?php echo T2; ?>gridAcciones2_btns">
    <!-- verificar permisos -->
    <?php if($nuevo["permiso"]): ?>
    <button id="<?php echo T2; ?>btnNewEmpleados2" type="button" onclick="" class="<?php echo $nuevo["theme"]; ?>">
        <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
    </button>
    <?php endif; ?>
</div>
<table  class="table table-striped table-hover table-condensed dataTable table-bordered" ></table>    
<?php echo SimpleForm::widgetClose(); ?>
<script>
axScript.removeAttr.click({
    container: "#"+tabs.T2+"gridAcciones2_tools",
    typeElement: "button"
});      
</script>