<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 18-03-2015 23:03:01 
* Descripcion : indexEmpleados.phtml
* ---------------------------------------
*/
    
echo SimpleForm::widgetOpen(array(
        "id"=>T2,
        "title"=>'acc'
    )); 
?>


<!--<div id="<?php echo T2; ?>gridAcciones2"></div>-->

<div id="<?php echo T2; ?>gridAcciones"></div>

<?php 
    echo SimpleForm::widgetClose(); 
