<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 18-03-2015 23:03:01 
* Descripcion : indexEmpleados.phtml
* ---------------------------------------
*/
    
echo AxForm::widgetOpen(array(
        "id"=>T2,
        "title"=>AXI_1
    )); 
?>


<!--<div id="<?php echo T2; ?>gridAcciones2"></div>-->

<div id="<?php echo T2; ?>gridAcciones"></div>

<?php 
    echo AxForm::widgetClose(); 
